name: shop_easy
description: "Aplicación móvil en Flutter que muestra una lista de productos desde una API pública."
publish_to: "none"

# Definir la versión mínima y máxima del SDK de Dart compatible
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6    # Para la gestión de estado
  dio: ^5.3.2                 # Para hacer peticiones HTTP
  cached_network_image: ^3.2.3 # Para manejar imágenes en caché
  infinite_scroll_pagination: ^5.0.0 # Para scroll infinito
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
